services:
  postgres-db1:
    image: postgres:18
    container_name: postgres-db1
    environment:
      POSTGRES_USER: yu71
      POSTGRES_PASSWORD: 53cret
      POSTGRES_DB: productdb
    ports:
      - "5435:5432"
    volumes:
      - ./postgres-db1-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U yu71 -d productdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - postgres-network

  postgres-db2:
    image: postgres:18
    container_name: postgres-db2
    environment:
      POSTGRES_USER: yu71
      POSTGRES_PASSWORD: 53cret
      POSTGRES_DB: productdb
    ports:
      - "5434:5432"
    volumes:
      - ./postgres-db2-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U yu71 -d productdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - postgres-network

volumes:
  postgres-db1-data:
  postgres-db2-data:

networks:
  postgres-network:
    driver: bridge
